# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

parameters:
  - name: succeed
    displayName: Succeed or fail
    type: boolean
    default: false
trigger:
- master

pool:
  name: Default
  demands:
   - agent.name -equals RunhuiLocalEnv

variables:
  buildConfiguration: 'Release'

jobs: 
- job: Work
  steps:
  - script: echo hello world
    displayName: 'one line script by runhui'
  
  - script: git clone malformed input
    condition: eq(${{parameters.succeed}}, false)

- job: ErrorHandler
  dependsOn: Work
  condition: failed()
  steps:
    - script: echo failel.oh on.
      displayName: 'Something need doing'
